camunda.bpm.admin-user:
  id: demo
  password: demo


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: 01100164092@yasmine22
    driver-class-name: com.mysql.cj.jdbc.Driver
process:
  xsdLocation: src/main/resources/core/xsd/UBL-Invoice-2.1.xsd
  enRulesLocation: /Users\YHamed\Desktop\AgileFolder\camundaP-processes\src\main\resources\core\en\CEN-EN16931-UBL.xsl
  ksaRulesLocation: /Users\YHamed\Desktop\AgileFolder\camundaP-processes\src\main\resources\core\ksa\20210819_ZATCA_E-invoice_Validation_Rules.xsl
publisherUrl: https://stzgw-apic-gov.gazt.gov.sa/e-invoicing/coreinv/kafka/publisher/invoices/publish
publisherPihUrl: https://stzgw-apic-gov.gazt.gov.sa/e-invoicing/coreinv/kafka/publisher/invoices/publishPIH
clearanceStatusUrl: https://stzgw-apic-gov.gazt.gov.sa/e-invoicing/admin/getMetaData
clearanceStatusByVatUrl: https://stzgw-apic-gov.gazt.gov.sa/e-invoicing/admin/adminConfig/api/lookups/v1/findByNameAndValue
businessRulesNameURL:  https://stzgw-apic-gov.gazt.gov.sa/e-invoicing/admin/adminConfig/api/lookups/v1/search/getErrorMessageByCode
compliance:
  checks:
    url: http://localhost:8011/core/csids/compliance/checks
zatca:
  signing:
    private:
      key: MHQCAQEEIPkmj0OfzMSx2ac4OwoFH8BKweT6EhLwSkQpK+m9yq+moAcGBSuBBAAKoUQDQgAER2J+N0nTdvf4zR1M+h9kJF8Er7wZ1uyeHDhM2YSppwcZO2tI1ptrdRWvNqY7LuFZkvaBQVD3Y25jB4bGGiK5jg==
    certificate: MIIB7DCCAZGgAwIBAgIGAX4qLf5RMAoGCCqGSM49BAMCMBUxEzARBgNVBAMMCmVJbnZvaWNpbmcwHhcNMjIwMTA1MTIxOTE5WhcNMjcwMTA0MjIwMDAwWjBOMQswCQYDVQQGEwJTQTEVMBMGA1UECwwMUnlpYWQgQnJhbmNoMQ4wDAYDVQQKDAVKZXJpcjEYMBYGA1UEAwwPMTIzNDU0MzIxMjEzMjM0MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAER2J+N0nTdvf4zR1M+h9kJF8Er7wZ1uyeHDhM2YSppwcZO2tI1ptrdRWvNqY7LuFZkvaBQVD3Y25jB4bGGiK5jqOBljCBkzAMBgNVHRMBAf8EAjAAMIGCBgNVHREEezB5pHcwdTEeMBwGA1UEBAwVMzM0MTMzMTMzMjMzMzMyMTIxMjAwMR8wHQYKCZImiZPyLGQBAQwPMzEwMTIyMzkzNTAwMDAzMQ0wCwYDVQQMDAQxMTAwMRIwEAYDVQQaDAlBZGRyZXNzZXMxDzANBgNVBA8MBlJldGFpbDAKBggqhkjOPQQDAgNJADBGAiEA/1gVN3gzxVkTn1Deiw7t1txwRWW9x0H/k4VbmpbQK08CIQC1zVWM6j5PDSZCaEaItr/XkW0kaixsemvVAipmz/K2zw==
certificate:
  authentication:
    url: http://localhost:8011/core/csids/auth
    v2:
      url: http://localhost:8012/core/auth/




